---
name: 'okta'
---
SilverStripe\Core\Injector\Injector:
  NZTA\Okta\Okta:
    factory: NZTA\Okta\OktaFactory
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        OktaMiddleware: '%$NZTA\Okta\OktaMiddleware'

SilverStripe\Security\Member:
  extensions:
    - 'NZTA\Okta\OktaMemberExtension'

SilverStripe\Control\Director:
  rules:
    'okta//$Action': 'NZTA\Okta\OktaController'

SilverStripe\Security\Security:
  logout_url: 'okta/slo'
